from pathlib import Path
import sys
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# Setup paths (kept for your environment consistency)
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

def classify_with_interpretability(comment: str, model, tok, device):
    prompt = (
        f"<|system|>Classify as 'Toxic' or 'Non-toxic'. Respond with one word.<|end|>\n"
        f"<|user|>{comment}<|end|>\n"
        f"<|assistant|>"
    )
    
    inputs = tok(prompt, return_tensors="pt").to(device)
    input_len = inputs['input_ids'].shape[1] # Number of tokens in your prompt
    input_tokens = tok.convert_ids_to_tokens(inputs['input_ids'][0])

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=5,
            do_sample=False,
            output_attentions=True,
            return_dict_in_generate=True 
        )
    
    # 1. FIX: Only decode the NEW tokens generated by the model
    generated_tokens = outputs.sequences[0][input_len:]
    answer = tok.decode(generated_tokens, skip_special_tokens=True).strip()

    # 2. Extract Attention
    if outputs.attentions is not None:
        # Get attention from the first generated token, last layer
        last_layer_attn = outputs.attentions[0][-1] 
        # Average heads and look at the attention over the INPUT tokens
        avg_attn = last_layer_attn.mean(dim=1)[0][-1] 
        
        # Pair tokens with their attention scores
        token_importance = sorted(
            zip(input_tokens, avg_attn.tolist()), 
            key=lambda x: x[1], 
            reverse=True
        )
    else:
        token_importance = []

    return answer, token_importance

def main() -> None:
    model_name = "microsoft/Phi-4-mini-instruct"
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    print(f"STATUS: Loading model '{model_name}' with Eager Attention...")
    
    # BYPASSING load_llm wrapper to ensure 'eager' implementation is used
    tok = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto",             # Automatically handles GPU placement
        torch_dtype=torch.float16,     # float16 is usually safer for VRAM than float32
        attn_implementation="eager"    # CRITICAL: Enables the output_attentions feature
    )
    
    print(f"STATUS: Connected to device: {model.device}")

    # Example test
    test_comment = "This is a stupid and hateful message!"
    label, importance = classify_with_interpretability(test_comment, model, tok, device)

    print("\n" + "="*40)
    print(f"COMMENT: {test_comment}")
    print(f"CLASSIFICATION: {label}")
    print("="*40)
    
    print("\nTOP TOKENS INFLUENCING THE DECISION:")
    count = 0
    for token, score in importance:
        # Filter out structural/special tokens for a cleaner report
        clean_token = token.replace(' ', ' ').strip()
        if clean_token and token not in ['<|', 'user', 'system', 'assistant', '>', '|', '\n']:
            print(f" - {token:<15} | Attention Score: {score:.4f}")
            count += 1
        if count >= 5: # Limit to top 5 meaningful tokens
            break

if __name__ == "__main__":
    main()